import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Trusted File Protection Suite",
  description: "Generated by ASHIK",
  openGraph: {
    title: "Trusted File Protection Suite",
    description: "Generated by ASHIK",
    siteName: "Trusted File Protection Suite",
  },
  other: {
    author: "ASHIK",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
